//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSharp.General.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedSharp.General.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be null or empty..
        /// </summary>
        internal static string Exception_CollectionIsNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_CollectionIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be null or white space..
        /// </summary>
        internal static string Exception_CollectionIsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Exception_CollectionIsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object of type: {0} - is already disposed..
        /// </summary>
        internal static string Exception_ObjectIsDisposed {
            get {
                return ResourceManager.GetString("Exception_ObjectIsDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be null or empty..
        /// </summary>
        internal static string Exception_StringIsNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_StringIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be null or white space..
        /// </summary>
        internal static string Exception_StringIsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Exception_StringIsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object is disposed..
        /// </summary>
        internal static string Exception_ThisObjectIsDisposed {
            get {
                return ResourceManager.GetString("Exception_ThisObjectIsDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value: {0} - cannot be equal to {1}..
        /// </summary>
        internal static string Exception_ValueIsEqual {
            get {
                return ResourceManager.GetString("Exception_ValueIsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value: {0} - is greater than {1}..
        /// </summary>
        internal static string Exception_ValueIsGreater {
            get {
                return ResourceManager.GetString("Exception_ValueIsGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value: {0} - is greater or equal to {1}..
        /// </summary>
        internal static string Exception_ValueIsGreaterOrEqual {
            get {
                return ResourceManager.GetString("Exception_ValueIsGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value: {0} - is less than {1}..
        /// </summary>
        internal static string Exception_ValueIsLess {
            get {
                return ResourceManager.GetString("Exception_ValueIsLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value: {0} - is less or equal to {1}..
        /// </summary>
        internal static string Exception_ValueIsLessOrEqual {
            get {
                return ResourceManager.GetString("Exception_ValueIsLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input object has incorrect type..
        /// </summary>
        internal static string Exception_WrongObjectType {
            get {
                return ResourceManager.GetString("Exception_WrongObjectType", resourceCulture);
            }
        }
    }
}
