//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSharp.General.Unmanaged.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedSharp.General.Unmanaged.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The allocation method returned an unexpected result..
        /// </summary>
        internal static string Exception_AllocationFailed {
            get {
                return ResourceManager.GetString("Exception_AllocationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handle for the object is already initialized..
        /// </summary>
        internal static string Exception_AlreadyHasHandle {
            get {
                return ResourceManager.GetString("Exception_AlreadyHasHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The memory for the structure is already allocated..
        /// </summary>
        internal static string Exception_IsAlreadyAllocated {
            get {
                return ResourceManager.GetString("Exception_IsAlreadyAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create shared memory object: {0}.
        /// </summary>
        internal static string Exception_PosixCannotCreateSharedObject {
            get {
                return ResourceManager.GetString("Exception_PosixCannotCreateSharedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to truncate shared memory object: {0}.
        /// </summary>
        internal static string Exception_PosixCannotTruncateSharedObject {
            get {
                return ResourceManager.GetString("Exception_PosixCannotTruncateSharedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input size is too big for the x86 application..
        /// </summary>
        internal static string Exception_SizeIsTooBig {
            get {
                return ResourceManager.GetString("Exception_SizeIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input size is too big for the stream object, the long.MaxValue is maximum..
        /// </summary>
        internal static string Exception_SizeIsTooBigForStream {
            get {
                return ResourceManager.GetString("Exception_SizeIsTooBigForStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input size has to be more or equal to the size of the wrapped structure..
        /// </summary>
        internal static string Exception_SizesAreNotCorrect {
            get {
                return ResourceManager.GetString("Exception_SizesAreNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object is disposed..
        /// </summary>
        internal static string Exception_ThisObjectIsDisposed {
            get {
                return ResourceManager.GetString("Exception_ThisObjectIsDisposed", resourceCulture);
            }
        }
    }
}
